version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MIX_ENV=dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PHX_HOST: ${PHX_HOST:-localhost}
    ports:
      - "4000:4000"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build

volumes:
  postgres_data: